//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDataService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AntonyEntities : DbContext
    {
        public AntonyEntities()
            : base("name=AntonyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Table_1> Table_1 { get; set; }
        public DbSet<Dept> Depts { get; set; }
        public DbSet<ChildTable> ChildTables { get; set; }
        public DbSet<ParentTable> ParentTables { get; set; }
    }
}
